// <auto-generated />
using System;
using MVC.Areas.Catalog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVC.Areas.Catalog.Data.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVC.Areas.Catalog.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Legumes"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Grains / Beans"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dairy products"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Meat & eggs"
                        });
                });

            modelBuilder.Entity("MVC.Areas.Catalog.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId");

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Code = "001",
                            Name = "Oranges",
                            Price = 5.90m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Code = "002",
                            Name = "Lemons",
                            Price = 5.90m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Code = "003",
                            Name = "Bananas",
                            Price = 6.90m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Code = "004",
                            Name = "Strawberries",
                            Price = 7.90m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Code = "005",
                            Name = "Grapes",
                            Price = 5.90m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Code = "006",
                            Name = "Carrots",
                            Price = 5.90m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Code = "007",
                            Name = "Yellow peppers",
                            Price = 8.90m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Code = "008",
                            Name = "Potatoes",
                            Price = 5.90m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Code = "009",
                            Name = "Tomatoes",
                            Price = 4.90m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Code = "010",
                            Name = "Eggplants",
                            Price = 5.90m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Code = "011",
                            Name = "Lettuce",
                            Price = 7.90m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Code = "012",
                            Name = "Broccoli",
                            Price = 5.90m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Code = "013",
                            Name = "Cauliflower",
                            Price = 4.90m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Code = "014",
                            Name = "Onion",
                            Price = 5.90m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Code = "015",
                            Name = "Aspargus",
                            Price = 8.90m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Code = "016",
                            Name = "Rice",
                            Price = 6.90m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Code = "017",
                            Name = "Beans",
                            Price = 6.90m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Code = "018",
                            Name = "Oat",
                            Price = 3.90m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Code = "019",
                            Name = "Corn",
                            Price = 3.90m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Code = "020",
                            Name = "Peas",
                            Price = 5.90m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            Code = "021",
                            Name = "Milk",
                            Price = 4.90m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            Code = "022",
                            Name = "Cheese",
                            Price = 8.90m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            Code = "023",
                            Name = "Yogurt",
                            Price = 6.90m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            Code = "024",
                            Name = "Butter",
                            Price = 5.90m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            Code = "025",
                            Name = "Cream cheese",
                            Price = 6.90m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 6,
                            Code = "026",
                            Name = "Sliced ham",
                            Price = 7.90m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 6,
                            Code = "027",
                            Name = "Beef",
                            Price = 6.90m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 6,
                            Code = "028",
                            Name = "Shrimp",
                            Price = 8.90m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 6,
                            Code = "029",
                            Name = "Barbecue",
                            Price = 6.90m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 6,
                            Code = "030",
                            Name = "Eggs",
                            Price = 4.90m
                        });
                });

            modelBuilder.Entity("MVC.Areas.Catalog.Models.Product", b =>
                {
                    b.HasOne("MVC.Areas.Catalog.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
